import logging
import os
import pathlib
import sys
from collections import OrderedDict
from typing import Any, Literal, Tuple

import pandas
import teradataml  # type: ignore
from dotenv import load_dotenv

from utils.logger import Logger


class TeradataConnection:
    """Teradata Connector."""

    def __init__(self, logger: logging.Logger) -> None:
        """Initialize Teradata connector.

        Args:
            logger (logging.Logger): A logger to log connector information
        """
        self._logger = logger
        self._logger.info("⏳ - Initializing connector...")

    @property
    def logger(self) -> logging.Logger:
        """Logger getter.

        Returns:
            logging.Logger: logger
        """
        return self._logger

    @logger.setter
    def logger(self, logger: logging.Logger) -> None:
        if type(logger) is logging.Logger:
            self._logger = logger

    def create_connection(self, host: str, user: str, pwd: str, db: str) -> bool:
        """Create connection with Teradata DB.

        Args:
            host (str): host name
            user (str): user to access the db
            pwd (str): user password
            db (str): default database
        """
        try:
            teradataml.create_context(  # type: ignore
                host=host,
                username=user,
                password=pwd,
                logmech="LDAP",
                database=db,
            )
            self.logger.info("✅ - Connection completed @ %s", host)
            return True
        except teradataml.TeradataMlException as e:
            self.logger.error("❌ - Connection error: %s", e)
            return False

    def close_connection(self) -> bool:
        """Closes Teradata Connection."""
        if teradataml.get_context() is not None:
            teradataml.remove_context()
            self.logger.info("✅ - Connection closed")
            return True
        self.logger.info("✅ - No connections opened")
        return False

    def fastload(
        self,
        dataframe: pandas.DataFrame,
        table: str,
        db: str,
        columns: OrderedDict[Any, Any],
        batch_size: int = 1_000_000,
        if_exists: Literal["append", "replace"] = "append",
        open_sessions: int = 2,
    ) -> pandas.DataFrame | None:
        """Uses fastload to upload data to DB.

        Args:
            dataframe (pandas.DataFrame): Dataframe containing data to upload
            table (str): Table name
            db (str): Database name
            columns (OrderedDict[Any, Any]): OrderedDict containing column name and type
            batch_size (int, optional): Size of batches. Defaults to 1_000_000.
            if_exists (Literal[&quot;append&quot;, &quot;replace&quot;], optional):
                What to do if table already exists. Defaults to "append".
            open_sessions (int, optional): Open sessions. Defaults to 2.

        Returns:
            pandas.DataFrame | None:
                Returns errors dataframe in case there are any erros or None
        """
        retry_count = 0
        try:
            result = teradataml.fastload(  # type: ignore
                dataframe,
                table,
                db,
                types=columns,
                if_exists=if_exists,
                batch_size=batch_size,
                open_sessions=open_sessions,
            )

            if not result["errors_dataframe"].empty:  # type: ignore
                self._save_errors(result["errors_dataframe"])  # type: ignore
                return result["errors_dataframe"]  # type: ignore
            self.logger.info("Informações enviadas com sucesso!")
            return None
        except teradataml.TeradataMlException as e:
            self.logger.error(
                "Não foi possível subir as informações. Erro encontrado: \n%s",
                e,
            )
            retry_count += 1
            if retry_count > 2:
                return None
            self.fastload(
                dataframe, table, db, columns, batch_size, if_exists, open_sessions
            )

    def _save_errors(self, dataframe: pandas.DataFrame) -> Tuple[int, int] | None:
        """Saves errors dataframes.

        Args:
            dataframe (pandas.DataFrame): Errors dataframe generated by fastload
        """
        if type(dataframe) is pandas.DataFrame:
            self.logger.info("Resultado do envio: %s", dataframe.head(1))

            self.__errors_path: pathlib.Path = pathlib.Path("errors")
            self.__errors_path.mkdir(exist_ok=True)
            dataframe.to_parquet("errors.parquet", index=False, compression="gzip")

            return dataframe.shape
        self.logger.info("Not a dataframe: %s", type(dataframe))
        return None


def main(args=None):  # type: ignore
    """Main entrypoint."""
    if args is None:
        args = sys.argv[1:]

    load_dotenv()

    HOST = str(os.getenv("TERADATA_HOST"))
    USER = str(os.getenv("TERADATA_USER"))
    PWD = str(os.getenv("TERADATA_PASSWORD"))
    DB = str(os.getenv("TERADATA_DB"))

    logger = Logger("test_job").get_logger()
    conn = TeradataConnection(logger)
    conn.create_connection(
        host=HOST,
        user=USER,
        pwd=PWD,
        db=DB,
    )
    conn.close_connection()
    return 0


if __name__ == "__main__":
    sys.exit(main())
